(function(){
'use strict';
var S={server:'http://127.0.0.1:8188',clientId:'comfyui_lab_'+Math.random().toString(16).slice(2),connected:false,ws:null,promptId:null,objectInfo:null,refs:{char:{file:null,serverName:'',previewUrl:''},pose:{file:null,serverName:'',previewUrl:''}}};
function q(id){return document.getElementById(id);}
function val(id,def){var x=q(id);return x&&x.value!==''?x.value:def;}
function setStatus(text,cls){var t=q('statusText');var d=q('statusDot');if(t){t.textContent=text;}if(d){d.className='status-dot '+(cls||'');}}
function log(msg){var box=q('logArea');var line='['+new Date().toLocaleTimeString()+'] '+msg;console.log(line);if(box){box.textContent+=line+'\n';box.scrollTop=box.scrollHeight;}}
function baseUrl(){var input=q('serverUrl');var url=input&&input.value?input.value.trim():'http://127.0.0.1:8188';if(url.indexOf('http://')!==0&&url.indexOf('https://')!==0){url='http://'+url;}url=url.replace(/\/+$/,'');if(input){input.value=url;}S.server=url;return url;}
function apiGet(path){return fetch(S.server+path,{cache:'no-store'}).then(function(r){if(!r.ok){throw new Error(path+' HTTP '+r.status);}return r.json();});}
function apiPost(path,obj){return fetch(S.server+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(obj||{})}).then(function(r){if(!r.ok){throw new Error(path+' HTTP '+r.status);}return r.text();}).then(function(t){return t?JSON.parse(t):{};});}
function uploadRef(key){var ref=S.refs[key];if(!ref||!ref.file){return Promise.resolve('');}if(ref.serverName){return Promise.resolve(ref.serverName);}var fd=new FormData();fd.append('image',ref.file,ref.file.name);fd.append('type','input');fd.append('overwrite','true');return fetch(S.server+'/upload/image',{method:'POST',body:fd}).then(function(r){if(!r.ok){throw new Error('/upload/image '+key+' HTTP '+r.status);}return r.json();}).then(function(j){ref.serverName=j.name||ref.file.name;log(key+' uploaded to ComfyUI input: '+ref.serverName);return ref.serverName;});}
function fillSelect(id,items){var s=q(id);if(!s){return;}s.innerHTML='';var blank=document.createElement('option');blank.value='';blank.textContent='';s.appendChild(blank);(items||[]).forEach(function(x){var o=document.createElement('option');o.value=x;o.textContent=x;s.appendChild(o);});if(s.options.length>1){s.selectedIndex=1;}}
function inputChoices(info,nodeName,keyName){try{var req=info[nodeName].input.required;if(keyName&&req[keyName]&&Array.isArray(req[keyName][0])){return req[keyName][0];}var keys=Object.keys(req);for(var i=0;i<keys.length;i++){if(Array.isArray(req[keys[i]])&&Array.isArray(req[keys[i]][0])){return req[keys[i]][0];}}}catch(e){}return[];}
function hasNode(name){return !!(S.objectInfo&&S.objectInfo[name]);}
function fillModels(info){fillSelect('selCheckpoint',inputChoices(info,'CheckpointLoaderSimple','ckpt_name'));fillSelect('selControlnet',inputChoices(info,'ControlNetLoader','control_net_name'));fillSelect('selIpadapter',inputChoices(info,'IPAdapterModelLoader','ipadapter_file'));fillSelect('selClipvision',inputChoices(info,'CLIPVisionLoader','clip_name'));}
function openWs(){try{if(S.ws){S.ws.close();}}catch(e){}var wsUrl=S.server.replace(/^http:/,'ws:').replace(/^https:/,'wss:')+'/ws?clientId='+encodeURIComponent(S.clientId);try{var ws=new WebSocket(wsUrl);S.ws=ws;ws.onopen=function(){log('WebSocket connected');};ws.onclose=function(){log('WebSocket closed');};ws.onerror=function(){log('WebSocket error');};ws.onmessage=function(ev){try{var m=JSON.parse(ev.data);if(m.type==='executing'&&m.data&&m.data.node===null&&m.data.prompt_id===S.promptId){loadHistory(S.promptId);}}catch(e){}};}catch(e){log('WebSocket open failed: '+e.message);}}
window.connectServer=function(){baseUrl();setStatus('Checking','connecting');log('Connecting '+S.server);return apiGet('/object_info').then(function(info){S.objectInfo=info;window.ComfyLabObjectInfo=info;fillModels(info);S.connected=true;setStatus('Connected','connected');var g=q('btnGenerate');if(g){g.disabled=false;}openWs();log('Connected. object_info nodes='+Object.keys(info).length);log('Reference support: LoadImage='+(hasNode('LoadImage')?'Y':'N')+', ControlNetApplyAdvanced='+(hasNode('ControlNetApplyAdvanced')?'Y':'N')+', IPAdapterAdvanced='+(hasNode('IPAdapterAdvanced')?'Y':'N'));}).catch(function(e){S.connected=false;setStatus('Disconnected','');var g=q('btnGenerate');if(g){g.disabled=true;}log('Connect failed: '+e.message);alert('ComfyUI 연결 실패: '+e.message);});};
function num(id,def){var n=Number(val(id,def));return isNaN(n)?def:n;}
function basicParams(){var ckpt=val('selCheckpoint','');if(!ckpt){throw new Error('Checkpoint를 먼저 선택하세요. Connect 후 목록이 비어 있으면 ComfyUI checkpoints 폴더를 확인하세요.');}var seed=parseInt(val('inSeed','-1'),10);if(isNaN(seed)||seed<0){seed=Math.floor(Math.random()*2147483647);}return{ckpt:ckpt,seed:seed,positive:val('positivePrompt','masterpiece, best quality'),negative:val('negativePrompt','low quality'),width:parseInt(num('inWidth',512),10),height:parseInt(num('inHeight',768),10),steps:parseInt(num('inSteps',25),10),cfg:num('inCfg',7),sampler:val('selSampler','dpmpp_2m'),scheduler:val('selScheduler','karras')};}
function buildWorkflow(refNames){var p=basicParams();var wf={'1':{class_type:'CheckpointLoaderSimple',inputs:{ckpt_name:p.ckpt}},'2':{class_type:'CLIPTextEncode',inputs:{text:p.positive,clip:['1',1]}},'3':{class_type:'CLIPTextEncode',inputs:{text:p.negative,clip:['1',1]}},'4':{class_type:'EmptyLatentImage',inputs:{width:p.width,height:p.height,batch_size:1}}};var modelOut=['1',0];var posOut=['2',0];var negOut=['3',0];var next=10;
if(refNames.pose&&val('selControlnet','')&&hasNode('LoadImage')&&hasNode('ControlNetLoader')&&hasNode('ControlNetApplyAdvanced')){var loadPose=String(next++), cn=String(next++), apply=String(next++);wf[loadPose]={class_type:'LoadImage',inputs:{image:refNames.pose}};wf[cn]={class_type:'ControlNetLoader',inputs:{control_net_name:val('selControlnet','')}};wf[apply]={class_type:'ControlNetApplyAdvanced',inputs:{positive:posOut,negative:negOut,control_net:[cn,0],image:[loadPose,0],strength:num('inCnStrength',0.82),start_percent:0,end_percent:num('inCnEnd',0.75)}};posOut=[apply,0];negOut=[apply,1];log('Pose reference applied through ControlNet: '+refNames.pose);}else if(refNames.pose){log('Pose reference preview/upload OK, but ControlNet workflow skipped. Check ControlNet node/model selection.');}
if(refNames.char&&val('selIpadapter','')&&hasNode('LoadImage')&&hasNode('IPAdapterModelLoader')&&hasNode('IPAdapterAdvanced')){var loadChar=String(next++), ipa=String(next++), applyIpa=String(next++);wf[loadChar]={class_type:'LoadImage',inputs:{image:refNames.char}};wf[ipa]={class_type:'IPAdapterModelLoader',inputs:{ipadapter_file:val('selIpadapter','')}};wf[applyIpa]={class_type:'IPAdapterAdvanced',inputs:{model:modelOut,ipadapter:[ipa,0],image:[loadChar,0],weight:num('inIpaWeight',0.4),weight_type:val('selIpaWeightType','linear'),start_at:num('inIpaStart',0.2),end_at:num('inIpaEnd',0.8),embeds_scaling:val('selEmbedsScaling','K+V w/ C penalty')}};modelOut=[applyIpa,0];log('Character reference applied through IPAdapter: '+refNames.char);}else if(refNames.char){log('Character reference preview/upload OK, but IPAdapter workflow skipped. Check IPAdapter node/model selection.');}
wf['5']={class_type:'KSampler',inputs:{seed:p.seed,steps:p.steps,cfg:p.cfg,sampler_name:p.sampler,scheduler:p.scheduler,denoise:1,model:modelOut,positive:posOut,negative:negOut,latent_image:['4',0]}};wf['6']={class_type:'VAEDecode',inputs:{samples:['5',0],vae:['1',2]}};wf['7']={class_type:'SaveImage',inputs:{filename_prefix:'comfyui_lab',images:['6',0]}};return wf;}
window.generate=function(){var btn=q('btnGenerate');var stop=q('btnInterrupt');if(btn){btn.disabled=true;}if(stop){stop.disabled=false;}var run=function(){Promise.all([uploadRef('char'),uploadRef('pose')]).then(function(names){queuePrompt({char:names[0],pose:names[1]});}).catch(function(e){log('Reference upload failed: '+e.message);alert('Reference upload 실패: '+e.message);finishRun();});};if(!S.connected){window.connectServer().then(run).catch(function(){finishRun();});}else{run();}};
function queuePrompt(refNames){try{var wf=buildWorkflow(refNames||{});apiPost('/prompt',{prompt:wf,client_id:S.clientId}).then(function(r){S.promptId=r.prompt_id;var info=q('genInfo');if(info){info.textContent='prompt '+S.promptId;}log('Queued prompt '+S.promptId);pollHistory(S.promptId,0);}).catch(function(e){log('Generate failed: '+e.message);alert('Generate 실패: '+e.message);finishRun();});}catch(e){log('Generate failed: '+e.message);alert(e.message);finishRun();}}
function finishRun(){var btn=q('btnGenerate');var stop=q('btnInterrupt');if(btn){btn.disabled=false;}if(stop){stop.disabled=true;}}
window.interrupt=function(){apiPost('/interrupt',{}).then(function(){log('Interrupt sent');}).catch(function(e){log('Interrupt failed: '+e.message);}).finally(finishRun);};
function pollHistory(pid,count){if(!pid||count>180){finishRun();return;}setTimeout(function(){loadHistory(pid,true).then(function(done){if(!done){pollHistory(pid,count+1);}}).catch(function(){pollHistory(pid,count+1);});},1000);}
function loadHistory(pid,silent){return apiGet('/history/'+encodeURIComponent(pid)).then(function(h){var item=h[pid];if(!item||!item.outputs){return false;}var img=null;Object.keys(item.outputs).forEach(function(k){var o=item.outputs[k];if(!img&&o.images&&o.images.length>0){img=o.images[0];}});if(!img){return false;}var url=S.server+'/view?filename='+encodeURIComponent(img.filename)+'&subfolder='+encodeURIComponent(img.subfolder||'')+'&type='+encodeURIComponent(img.type||'output')+'&t='+Date.now();var gallery=q('gallery');if(gallery){var im=document.createElement('img');im.src=url;im.title=img.filename;im.onclick=function(){window.open(url,'_blank');};gallery.insertBefore(im,gallery.firstChild);}log('Image loaded '+img.filename);finishRun();return true;}).catch(function(e){if(!silent){log('History load failed: '+e.message);}return false;});}
window.showAdvancedDialog=function(){var modal=q('advancedModal');var grid=q('advancedGrid');if(grid){grid.innerHTML='<label class="ctrl"><span>Server</span><input type="text" readonly value="'+S.server+'"></label><label class="ctrl"><span>Connected</span><input type="text" readonly value="'+S.connected+'"></label><label class="ctrl"><span>ClientId</span><input type="text" readonly value="'+S.clientId+'"></label><label class="ctrl"><span>Checkpoint count</span><input type="text" readonly value="'+(q('selCheckpoint')?Math.max(0,q('selCheckpoint').options.length-1):0)+'"></label><label class="ctrl"><span>Character ref</span><input type="text" readonly value="'+(S.refs.char.file?S.refs.char.file.name:'none')+'"></label><label class="ctrl"><span>Pose ref</span><input type="text" readonly value="'+(S.refs.pose.file?S.refs.pose.file.name:'none')+'"></label>';}
if(modal){modal.classList.add('show');}else{alert('Advanced loaded');}};
window.closeAdvancedDialog=function(){var m=q('advancedModal');if(m){m.classList.remove('show');}};
window.applyAdvancedSettings=function(){window.closeAdvancedDialog();};
window.handleUpload=function(input,key){if(!input.files||!input.files[0]){return;}var ref=S.refs[key];ref.file=input.files[0];ref.serverName='';if(ref.previewUrl){try{URL.revokeObjectURL(ref.previewUrl);}catch(e){}}ref.previewUrl=URL.createObjectURL(ref.file);var target=q(key==='char'?'previewChar':'previewPose');if(target){target.innerHTML='<div style="font-size:11px;margin-bottom:6px;color:#a29bfe">'+ref.file.name+'</div><img src="'+ref.previewUrl+'" style="max-width:100%;max-height:150px;border-radius:6px;display:block;margin:auto;object-fit:contain">';}log(key+' image selected '+ref.file.name+' / preview visible');};
window.saveCurrentPreset=function(){var p={positive:val('positivePrompt',''),negative:val('negativePrompt',''),width:val('inWidth','512'),height:val('inHeight','768'),steps:val('inSteps','25'),cfg:val('inCfg','7')};localStorage.setItem('comfyui_lab_preset',JSON.stringify(p));log('Preset saved');};
window.applyProfile=function(name){if(name==='quality'){q('inSteps').value=35;q('inCfg').value=7.5;}else if(name==='speed'){q('inSteps').value=12;q('inCfg').value=6;}else{q('inSteps').value=25;q('inCfg').value=7;}log('Profile '+name);};
log('hotfix.js loaded: reference preview/upload enabled');
})();
