(function(){
'use strict';
function q(id){return document.getElementById(id);}
function log(m){var b=q('logArea');var s='['+new Date().toLocaleTimeString()+'] '+m;console.log(s);if(b){b.textContent+=s+'\n';b.scrollTop=b.scrollHeight;}}
function base(){var u=(q('serverUrl')&&q('serverUrl').value?q('serverUrl').value:'http://127.0.0.1:8188').trim();return u.replace(/\/+$/,'');}
function v(id,d){var x=q(id);return x&&x.value!==''?x.value:d;}
function n(id,d){var x=Number(v(id,d));return isNaN(x)?d:x;}
function hasNode(name){return !!(window.ComfyLabObjectInfo&&window.ComfyLabObjectInfo[name]);}
function post(path,obj){return fetch(base()+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(obj)}).then(function(r){if(!r.ok){throw new Error(path+' HTTP '+r.status);}return r.json();});}
function get(path){return fetch(base()+path,{cache:'no-store'}).then(function(r){if(!r.ok){throw new Error(path+' HTTP '+r.status);}return r.json();});}
function selectedFile(id){var x=q(id);return x&&x.files&&x.files[0]?x.files[0]:null;}
function uploadInput(file){if(!file){return Promise.resolve('');}var fd=new FormData();fd.append('image',file,file.name);fd.append('type','input');fd.append('overwrite','true');return fetch(base()+'/upload/image',{method:'POST',body:fd}).then(function(r){if(!r.ok){throw new Error('upload HTTP '+r.status);}return r.json();}).then(function(j){return j.name||file.name;});}
function esc(s){return String(s||'').replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c];});}
var L={shots:[],urls:[],playing:false,charName:''};
function inject(){var center=document.querySelector('.panel-center');if(!center||q('llmProdPanel')){return;}var panel=document.createElement('div');panel.id='llmProdPanel';panel.style.cssText='background:#10131d;border-bottom:1px solid #46506c;padding:10px;display:grid;grid-template-columns:1fr 1fr;gap:10px;max-height:430px;overflow:auto';panel.innerHTML='<div><div style="display:flex;gap:7px;align-items:center;margin-bottom:6px;flex-wrap:wrap"><b style="color:#00cec9">LLM Shot Card Pipeline</b><button class="btn btn-sm btn-primary" id="btnCopyPlanner">Copy LLM Planner Prompt</button><button class="btn btn-sm" id="btnImportShots">Import Shot JSON</button><button class="btn btn-sm btn-accent" id="btnGenImported">Generate Imported Images</button><button class="btn btn-sm" id="btnPlayImported">Play Preview</button></div><textarea id="llmScenario" rows="6" placeholder="시나리오 원문. 버튼을 누르면 외부 LLM에 붙여넣을 엄격한 Shot Card JSON 생성 프롬프트가 복사됩니다." style="width:100%;background:#242436;border:1px solid #333348;color:#dfe6e9;border-radius:8px;padding:8px"></textarea><textarea id="llmShotJson" rows="7" placeholder="외부 LLM이 반환한 JSON을 여기에 붙여넣고 Import Shot JSON을 누르세요." style="width:100%;margin-top:6px;background:#181a28;border:1px solid #333348;color:#dfe6e9;border-radius:8px;padding:8px;font-family:Consolas,monospace;font-size:11px"></textarea></div><div><div id="llmShotList" style="height:190px;overflow:auto;border:1px solid #333348;border-radius:8px;padding:6px;background:#080a10;font-size:11px"></div><canvas id="llmTimelineCanvas" width="960" height="540" style="width:100%;margin-top:8px;background:#050509;border:1px solid #333348;border-radius:8px"></canvas></div>';center.insertBefore(panel, center.firstChild);q('btnCopyPlanner').onclick=copyPlannerPrompt;q('btnImportShots').onclick=importShots;q('btnGenImported').onclick=generateAll;q('btnPlayImported').onclick=playPreview;log('llm_production.js loaded: external LLM shot-card import pipeline ready');}
function plannerPrompt(){var scenario=v('llmScenario','').trim()||v('scenarioText','').trim();var style=v('prodStyle','cinematic anime wuxia, dramatic lighting, detailed, clean lineart');return '당신은 영상 콘티/이미지 생성 프롬프트 설계자입니다. 아래 시나리오를 3~5초 단위의 이미지 생성용 Shot Card로 분해하세요.\n\n중요 목표:\n- 얼굴/복장은 사용자가 제공하는 character reference 이미지가 담당합니다.\n- visual_prompt는 장면, 동작, 카메라, 배경, 분위기, 소품을 구체적으로 지시합니다.\n- 한 shot에는 하나의 명확한 행동만 넣습니다.\n- 대본 내용과 무관한 장면을 만들지 않습니다.\n- 이미지 생성 모델이 잘 따를 수 있도록 영어 프롬프트로 작성합니다.\n- subtitle은 한국어 자막으로 자연스럽게 작성합니다.\n- 반환은 JSON만 출력합니다. 설명, 마크다운, 코드블록 금지.\n\n반환 스키마:\n{\n  "project_title": "string",\n  "style_bible": "'+style.replace(/"/g,'\\"')+'",\n  "negative_prompt": "low quality, blurry, bad anatomy, extra fingers, deformed fingers, text, watermark",\n  "shots": [\n    {\n      "shot_id": "S001",\n      "order": 1,\n      "duration_sec": 4,\n      "scene_text": "원문 장면 요약",\n      "subtitle": "한국어 자막",\n      "visual_prompt": "English image prompt focused on action, scene, camera, atmosphere, props",\n      "workflow_mode": "Character Stable Scene | Action Wide Shot | Dialogue Close-up | Background / Establishing Shot | Exact Pose Scene",\n      "exact_pose_required": false,\n      "camera": "close-up | medium shot | full body | wide shot | low angle | high angle",\n      "status": "pending"\n    }\n  ]\n}\n\n시나리오:\n'+scenario;}
function copyPlannerPrompt(){var p=plannerPrompt();navigator.clipboard.writeText(p).then(function(){log('External LLM planner prompt copied to clipboard');}).catch(function(){q('llmShotJson').value=p;log('Clipboard blocked. Planner prompt inserted into JSON box instead.');});}
function normalizeShot(s,i,neg){return {shot_id:String(s.shot_id||('S'+String(i+1).padStart(3,'0'))),order:Number(s.order||i+1),duration_sec:Number(s.duration_sec||4),scene_text:String(s.scene_text||s.subtitle||''),subtitle:String(s.subtitle||s.scene_text||''),visual_prompt:String(s.visual_prompt||s.prompt||s.scene_text||''),workflow_mode:String(s.workflow_mode||'Character Stable Scene'),exact_pose_required:!!s.exact_pose_required,camera:String(s.camera||''),negative_prompt:String(s.negative_prompt||neg||v('negativePrompt','low quality, blurry, bad anatomy')),status:'pending',image_url:''};}
function extractJson(text){var t=String(text||'').trim();if(!t){throw new Error('Shot JSON is empty');}if(t.indexOf('```')>=0){t=t.replace(/```json/gi,'').replace(/```/g,'').trim();}var a=t.indexOf('{'),b=t.lastIndexOf('}');var aa=t.indexOf('['),bb=t.lastIndexOf(']');if(a>=0&&b>a){t=t.slice(a,b+1);}else if(aa>=0&&bb>aa){t=t.slice(aa,bb+1);}return JSON.parse(t);}
function importShots(){try{var data=extractJson(v('llmShotJson',''));var list=Array.isArray(data)?data:(Array.isArray(data.shots)?data.shots:[]);var neg=Array.isArray(data)?'':data.negative_prompt;L.shots=list.map(function(s,i){return normalizeShot(s,i,neg);});L.urls=[];render();log('Imported LLM shot cards: '+L.shots.length);}catch(e){log('Import failed: '+e.message);alert('Shot JSON Import 실패: '+e.message);}}
function render(){var box=q('llmShotList');if(!box){return;}box.innerHTML='';L.shots.forEach(function(s){var d=document.createElement('div');d.style.cssText='border-bottom:1px solid #333348;padding:5px 2px;color:#dfe6e9';d.innerHTML='<b style="color:#00cec9">'+esc(s.shot_id)+'</b> <span style="color:#a29bfe">'+esc(s.workflow_mode)+'</span> <span style="color:#8b93a7">'+esc(s.status)+'</span><br><span style="color:#fff">'+esc(s.subtitle)+'</span><br><span style="color:#8b93a7">'+esc(s.visual_prompt).slice(0,220)+'</span>';box.appendChild(d);});}
function wf(s,charName){var ckpt=v('selCheckpoint','');if(!ckpt){throw new Error('Checkpoint required');}var prompt=s.visual_prompt+', '+v('prodStyle','cinematic anime wuxia, dramatic lighting, detailed, clean lineart');var w={'1':{class_type:'CheckpointLoaderSimple',inputs:{ckpt_name:ckpt}},'2':{class_type:'CLIPTextEncode',inputs:{text:prompt,clip:['1',1]}},'3':{class_type:'CLIPTextEncode',inputs:{text:s.negative_prompt||v('negativePrompt','low quality, blurry, bad anatomy'),clip:['1',1]}},'4':{class_type:'EmptyLatentImage',inputs:{width:parseInt(n('inWidth',512),10),height:parseInt(n('inHeight',768),10),batch_size:1}}};var model=['1',0],next=10;if(charName&&v('selIpadapter','')&&v('selClipvision','')&&hasNode('IPAdapterAdvanced')){var lc=''+next++,ip=''+next++,cv=''+next++,ai=''+next++;w[lc]={class_type:'LoadImage',inputs:{image:charName}};w[ip]={class_type:'IPAdapterModelLoader',inputs:{ipadapter_file:v('selIpadapter','')}};w[cv]={class_type:'CLIPVisionLoader',inputs:{clip_name:v('selClipvision','')}};w[ai]={class_type:'IPAdapterAdvanced',inputs:{model:model,ipadapter:[ip,0],clip_vision:[cv,0],image:[lc,0],weight:0.50,weight_type:'linear',combine_embeds:'concat',start_at:0.10,end_at:0.85,embeds_scaling:'K+V w/ C penalty'}};model=[ai,0];}w['5']={class_type:'KSampler',inputs:{seed:Math.floor(Math.random()*2147483647),steps:parseInt(n('inSteps',22),10),cfg:n('inCfg',6.5),sampler_name:v('selSampler','dpmpp_2m'),scheduler:v('selScheduler','karras'),denoise:1,model:model,positive:['2',0],negative:['3',0],latent_image:['4',0]}};w['6']={class_type:'VAEDecode',inputs:{samples:['5',0],vae:['1',2]}};w['7']={class_type:'SaveImage',inputs:{filename_prefix:'llm_shot',images:['6',0]}};return w;}
function waitImage(pid,limit){var c=0;return new Promise(function(resolve,reject){function tick(){c++;get('/history/'+encodeURIComponent(pid)).then(function(h){var it=h[pid],img=null;if(it&&it.outputs){Object.keys(it.outputs).forEach(function(k){var o=it.outputs[k];if(!img&&o.images&&o.images[0]){img=o.images[0];}});}if(img){resolve(base()+'/view?filename='+encodeURIComponent(img.filename)+'&subfolder='+encodeURIComponent(img.subfolder||'')+'&type='+encodeURIComponent(img.type||'output')+'&t='+Date.now());return;}if(c>limit){reject(new Error('timeout'));return;}setTimeout(tick,1000);}).catch(function(){if(c>limit){reject(new Error('history failed'));}else{setTimeout(tick,1000);}});}tick();});}
function genOne(i){var s=L.shots[i];s.status='generating';render();return post('/prompt',{prompt:wf(s,L.charName),client_id:'llm_movie_builder'}).then(function(r){log('Queued '+s.shot_id+' '+r.prompt_id);return waitImage(r.prompt_id,180);}).then(function(url){s.image_url=url;L.urls[i]=url;s.status='done';render();draw(i);log('Done '+s.shot_id);}).catch(function(e){s.status='failed: '+e.message;render();log('Failed '+s.shot_id+' '+e.message);});}
function generateAll(){if(L.shots.length===0){importShots();}if(L.shots.length===0){alert('먼저 외부 LLM Shot JSON을 Import 하세요.');return;}uploadInput(selectedFile('fileChar')).then(function(name){L.charName=name;var chain=Promise.resolve();L.shots.forEach(function(_,i){chain=chain.then(function(){return genOne(i);});});return chain;}).then(function(){log('LLM shot batch generation finished');playPreview();}).catch(function(e){log('Batch failed: '+e.message);alert(e.message);});}
function draw(i){var c=q('llmTimelineCanvas');if(!c){return;}var ctx=c.getContext('2d'),s=L.shots[i];ctx.fillStyle='#050509';ctx.fillRect(0,0,c.width,c.height);if(!s){return;}var img=new Image();img.crossOrigin='anonymous';img.onload=function(){ctx.fillStyle='#050509';ctx.fillRect(0,0,c.width,c.height);var r=Math.min(c.width/img.width,c.height/img.height);var w=img.width*r,h=img.height*r,x=(c.width-w)/2,y=(c.height-h)/2;ctx.drawImage(img,x,y,w,h);caption(ctx,c,s);};img.src=s.image_url||'';if(!s.image_url){caption(ctx,c,s);}}
function caption(ctx,c,s){ctx.fillStyle='rgba(0,0,0,.65)';ctx.fillRect(0,c.height-96,c.width,96);ctx.fillStyle='#fff';ctx.font='30px Malgun Gothic, Segoe UI';ctx.textAlign='center';wrap(ctx,s.subtitle,c.width/2,c.height-55,c.width-80,34);ctx.fillStyle='#00cec9';ctx.font='18px Segoe UI';ctx.fillText(s.shot_id+'  '+s.workflow_mode,c.width/2,30);}
function wrap(ctx,text,x,y,max,lineH){var words=String(text||'').split(' '),line='';for(var i=0;i<words.length;i++){var test=line+words[i]+' ';if(ctx.measureText(test).width>max&&i>0){ctx.fillText(line,x,y);line=words[i]+' ';y+=lineH;}else{line=test;}}ctx.fillText(line,x,y);}
function playPreview(){if(L.shots.length===0){return;}var i=0;L.playing=true;function step(){if(!L.playing){return;}draw(i);setTimeout(function(){i=(i+1)%L.shots.length;step();},(L.shots[i].duration_sec||4)*1000);}step();}
setTimeout(inject,600);
})();