(function(){
'use strict';
function q(id){return document.getElementById(id);}
function log(m){var b=q('logArea');var s='['+new Date().toLocaleTimeString()+'] '+m;console.log(s);if(b){b.textContent+=s+'\n';b.scrollTop=b.scrollHeight;}}
function base(){var u=(q('serverUrl')&&q('serverUrl').value?q('serverUrl').value:'http://127.0.0.1:8188').trim();return u.replace(/\/+$/,'');}
function v(id,d){var x=q(id);return x&&x.value!==''?x.value:d;}
function n(id,d){var x=Number(v(id,d));return isNaN(x)?d:x;}
function hasNode(name){return !!(window.ComfyLabObjectInfo&&window.ComfyLabObjectInfo[name]);}
function post(path,obj){return fetch(base()+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(obj)}).then(function(r){if(!r.ok){throw new Error(path+' HTTP '+r.status);}return r.json();});}
function get(path){return fetch(base()+path,{cache:'no-store'}).then(function(r){if(!r.ok){throw new Error(path+' HTTP '+r.status);}return r.json();});}
function uploadInput(file){if(!file){return Promise.resolve('');}var fd=new FormData();fd.append('image',file,file.name);fd.append('type','input');fd.append('overwrite','true');return fetch(base()+'/upload/image',{method:'POST',body:fd}).then(function(r){if(!r.ok){throw new Error('upload HTTP '+r.status);}return r.json();}).then(function(j){return j.name||file.name;});}
function selectedFile(id){var x=q(id);return x&&x.files&&x.files[0]?x.files[0]:null;}
function esc(s){return String(s||'').replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c];});}
var P={shots:[],results:[],playing:false};
function inject(){
 var center=document.querySelector('.panel-center');if(!center||q('prodPanel')){return;}
 var panel=document.createElement('div');panel.id='prodPanel';panel.style.cssText='background:#151620;border-bottom:1px solid #333348;padding:10px;display:grid;grid-template-columns:1.1fr .9fr;gap:10px;max-height:360px;overflow:auto';
 panel.innerHTML='<div><div style="display:flex;gap:8px;align-items:center;margin-bottom:6px"><b style="color:#a29bfe">Production Movie Builder</b><button class="btn btn-sm btn-primary" id="btnBuildShots">Generate Shot Cards</button><button class="btn btn-sm btn-accent" id="btnBatchGen">Generate All Images</button><button class="btn btn-sm" id="btnPlayTimeline">Play Preview</button><button class="btn btn-sm" id="btnExportWebm">Export WebM</button></div><textarea id="scenarioText" rows="8" placeholder="여기에 무협/영상 시나리오를 붙여넣으세요. 한 문장 또는 한 단락이 하나의 장면 후보가 됩니다." style="width:100%;background:#242436;border:1px solid #333348;color:#dfe6e9;border-radius:8px;padding:8px"></textarea><div style="display:grid;grid-template-columns:120px 1fr 120px 1fr;gap:6px;margin-top:6px;font-size:11px;color:#8b93a7"><label>Scene Style</label><input id="prodStyle" value="cinematic anime wuxia, dramatic lighting, detailed, clean lineart" style="background:#242436;color:#dfe6e9;border:1px solid #333348;border-radius:4px;padding:4px"><label>Duration</label><input id="prodDuration" type="number" value="4" min="2" max="10" style="background:#242436;color:#dfe6e9;border:1px solid #333348;border-radius:4px;padding:4px"></div></div><div><div id="shotList" style="height:170px;overflow:auto;border:1px solid #333348;border-radius:8px;padding:6px;background:#0f0f13;font-size:11px"></div><canvas id="timelineCanvas" width="960" height="540" style="width:100%;margin-top:8px;background:#050509;border:1px solid #333348;border-radius:8px"></canvas></div>';
 center.insertBefore(panel, center.firstChild);
 q('btnBuildShots').onclick=buildShots;q('btnBatchGen').onclick=batchGenerate;q('btnPlayTimeline').onclick=playTimeline;q('btnExportWebm').onclick=exportWebm;
 log('production.js loaded: scenario to image timeline pipeline ready');
}
function splitScenario(text){
 var raw=String(text||'').replace(/\r/g,'\n').split(/\n+/).map(function(x){return x.trim();}).filter(Boolean);
 if(raw.length<=1){raw=String(text||'').split(/(?<=[.!?。！？다요였다했다한다])\s+/).map(function(x){return x.trim();}).filter(Boolean);}return raw;
}
function shotType(t){var s=t.toLowerCase();if(/검|sword|칼|창|spear|attack|fight|duel|slash|raise|높이|휘두|전투|결투/.test(s)){return 'Action Wide Shot';}if(/말했|속삭|dialogue|said|whisper|눈빛|close|face|얼굴/.test(s)){return 'Dialogue Close-up';}if(/산|밤|달|비|숲|궁|배경|establish|wide|city|temple/.test(s)){return 'Background / Establishing Shot';}return 'Character Stable Scene';}
function promptFor(t,type){var style=v('prodStyle','cinematic anime wuxia, dramatic lighting');var action=t.replace(/["']/g,'');var camera='medium shot';if(type==='Action Wide Shot'){camera='dynamic full body action shot, strong silhouette, motion lines';}if(type==='Dialogue Close-up'){camera='emotional close-up portrait, expressive eyes';}if(type==='Background / Establishing Shot'){camera='wide establishing shot, environment focus';}return action+', '+camera+', '+style;}
function buildShots(){var parts=splitScenario(v('scenarioText',''));P.shots=[];P.results=[];var dur=Math.max(2,Math.min(10,parseInt(v('prodDuration','4'),10)||4));for(var i=0;i<parts.length;i++){var type=shotType(parts[i]);P.shots.push({shot_id:'S'+String(i+1).padStart(3,'0'),order:i+1,duration_sec:dur,scene_text:parts[i],subtitle:parts[i],visual_prompt:promptFor(parts[i],type),workflow_mode:type,status:'pending',image_url:''});}
 renderShots();log('Shot cards generated: '+P.shots.length);}
function renderShots(){var box=q('shotList');if(!box){return;}box.innerHTML='';P.shots.forEach(function(s){var d=document.createElement('div');d.style.cssText='border-bottom:1px solid #333348;padding:5px 2px;color:#dfe6e9';d.innerHTML='<b style="color:#00cec9">'+s.shot_id+'</b> <span style="color:#a29bfe">'+esc(s.workflow_mode)+'</span> <span style="color:#8b93a7">'+s.status+'</span><br><span>'+esc(s.subtitle)+'</span>';box.appendChild(d);});}
function workflow(prompt,charName){var ckpt=v('selCheckpoint','');if(!ckpt){throw new Error('Checkpoint required');}var seed=Math.floor(Math.random()*2147483647);var w={'1':{class_type:'CheckpointLoaderSimple',inputs:{ckpt_name:ckpt}},'2':{class_type:'CLIPTextEncode',inputs:{text:prompt,clip:['1',1]}},'3':{class_type:'CLIPTextEncode',inputs:{text:v('negativePrompt','low quality, blurry, bad anatomy'),clip:['1',1]}},'4':{class_type:'EmptyLatentImage',inputs:{width:parseInt(n('inWidth',512),10),height:parseInt(n('inHeight',768),10),batch_size:1}}};var model=['1',0],next=10;if(charName&&v('selIpadapter','')&&v('selClipvision','')&&hasNode('IPAdapterAdvanced')){var lc=''+next++,ip=''+next++,cv=''+next++,ai=''+next++;w[lc]={class_type:'LoadImage',inputs:{image:charName}};w[ip]={class_type:'IPAdapterModelLoader',inputs:{ipadapter_file:v('selIpadapter','')}};w[cv]={class_type:'CLIPVisionLoader',inputs:{clip_name:v('selClipvision','')}};w[ai]={class_type:'IPAdapterAdvanced',inputs:{model:model,ipadapter:[ip,0],clip_vision:[cv,0],image:[lc,0],weight:0.48,weight_type:'linear',combine_embeds:'concat',start_at:0.15,end_at:0.85,embeds_scaling:'K+V w/ C penalty'}};model=[ai,0];}
w['5']={class_type:'KSampler',inputs:{seed:seed,steps:parseInt(n('inSteps',22),10),cfg:n('inCfg',6.5),sampler_name:v('selSampler','dpmpp_2m'),scheduler:v('selScheduler','karras'),denoise:1,model:model,positive:['2',0],negative:['3',0],latent_image:['4',0]}};w['6']={class_type:'VAEDecode',inputs:{samples:['5',0],vae:['1',2]}};w['7']={class_type:'SaveImage',inputs:{filename_prefix:'movie_shot',images:['6',0]}};return w;}
function waitImage(pid,limit){var c=0;return new Promise(function(resolve,reject){function tick(){c++;get('/history/'+encodeURIComponent(pid)).then(function(h){var it=h[pid],img=null;if(it&&it.outputs){Object.keys(it.outputs).forEach(function(k){var o=it.outputs[k];if(!img&&o.images&&o.images[0]){img=o.images[0];}});}if(img){var u=base()+'/view?filename='+encodeURIComponent(img.filename)+'&subfolder='+encodeURIComponent(img.subfolder||'')+'&type='+encodeURIComponent(img.type||'output')+'&t='+Date.now();resolve(u);return;}if(c>limit){reject(new Error('timeout'));return;}setTimeout(tick,1200);}).catch(function(){if(c>limit){reject(new Error('history failed'));}else{setTimeout(tick,1200);}});}tick();});}
function generateOne(idx,charName){var s=P.shots[idx];s.status='generating';renderShots();return post('/prompt',{prompt:workflow(s.visual_prompt,charName),client_id:'movie_builder'}).then(function(r){log('Queued '+s.shot_id+' '+r.prompt_id);return waitImage(r.prompt_id,160);}).then(function(url){s.image_url=url;s.status='done';P.results[idx]=url;renderShots();drawFrame(idx);log('Done '+s.shot_id);}).catch(function(e){s.status='failed: '+e.message;renderShots();log('Failed '+s.shot_id+' '+e.message);});}
function batchGenerate(){if(P.shots.length===0){buildShots();}if(P.shots.length===0){alert('시나리오를 입력하세요.');return;}uploadInput(selectedFile('fileChar')).then(function(charName){var chain=Promise.resolve();P.shots.forEach(function(_,i){chain=chain.then(function(){return generateOne(i,charName);});});return chain;}).then(function(){log('Batch generation finished');playTimeline();}).catch(function(e){log('Batch failed '+e.message);alert(e.message);});}
function drawFrame(idx){var c=q('timelineCanvas');if(!c){return;}var ctx=c.getContext('2d');ctx.fillStyle='#050509';ctx.fillRect(0,0,c.width,c.height);var s=P.shots[idx];if(!s){return;}var img=new Image();img.crossOrigin='anonymous';img.onload=function(){ctx.fillStyle='#050509';ctx.fillRect(0,0,c.width,c.height);var rw=c.width/img.width,rh=c.height/img.height,r=Math.min(rw,rh);var w=img.width*r,h=img.height*r,x=(c.width-w)/2,y=(c.height-h)/2;ctx.drawImage(img,x,y,w,h);drawCaption(ctx,c,s.subtitle,s.shot_id+'  '+s.workflow_mode);};img.src=s.image_url||'';if(!s.image_url){drawCaption(ctx,c,s.subtitle,s.shot_id+'  '+s.workflow_mode);}}
function drawCaption(ctx,c,sub,top){ctx.fillStyle='rgba(0,0,0,.62)';ctx.fillRect(0,c.height-92,c.width,92);ctx.fillStyle='#fff';ctx.font='30px Malgun Gothic, Segoe UI';ctx.textAlign='center';wrap(ctx,sub,c.width/2,c.height-52,c.width-80,34);ctx.fillStyle='#00cec9';ctx.font='18px Segoe UI';ctx.fillText(top,c.width/2,30);}
function wrap(ctx,text,x,y,max,lineH){var words=String(text||'').split(' '),line='';for(var i=0;i<words.length;i++){var test=line+words[i]+' ';if(ctx.measureText(test).width>max&&i>0){ctx.fillText(line,x,y);line=words[i]+' ';y+=lineH;}else{line=test;}}ctx.fillText(line,x,y);}
function playTimeline(){if(P.shots.length===0){return;}var i=0;P.playing=true;function step(){if(!P.playing){return;}drawFrame(i);var d=(P.shots[i].duration_sec||4)*1000;i=(i+1)%P.shots.length;setTimeout(step,d);}step();}
function exportWebm(){var c=q('timelineCanvas');if(!c||P.shots.length===0){alert('생성된 shot이 없습니다.');return;}var stream=c.captureStream(24);var rec=new MediaRecorder(stream,{mimeType:'video/webm'});var chunks=[];rec.ondataavailable=function(e){if(e.data.size>0){chunks.push(e.data);}};rec.onstop=function(){var blob=new Blob(chunks,{type:'video/webm'});var a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='comfyui_lab_preview.webm';a.click();};var idx=0;rec.start();function next(){if(idx>=P.shots.length){rec.stop();return;}drawFrame(idx);setTimeout(function(){idx++;next();},(P.shots[idx].duration_sec||4)*1000);}next();}
setTimeout(inject,300);
})();