(function(){
'use strict';
function q(id){return document.getElementById(id);}
function v(id,d){var x=q(id);return x&&x.value!==''?x.value:d;}
function log(m){var b=q('logArea');var s='['+new Date().toLocaleTimeString()+'] '+m;console.log(s);if(b){b.textContent+=s+'\n';b.scrollTop=b.scrollHeight;}}
function base(){var u=v('serverUrl','http://127.0.0.1:8188');return u.replace(/\/+$/,'');}
function post(path,obj){return fetch(base()+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(obj)}).then(function(r){if(!r.ok){throw new Error(path+' HTTP '+r.status);}return r.json();});}
function get(path){return fetch(base()+path,{cache:'no-store'}).then(function(r){if(!r.ok){throw new Error(path+' HTTP '+r.status);}return r.json();});}
function n(id,d){var x=Number(v(id,d));return isNaN(x)?d:x;}
function hasNode(name){return !!(window.ComfyLabObjectInfo&&window.ComfyLabObjectInfo[name]);}
function uploadInput(file){if(!file){return Promise.resolve('');}var fd=new FormData();fd.append('image',file,file.name);fd.append('type','input');fd.append('overwrite','true');return fetch(base()+'/upload/image',{method:'POST',body:fd}).then(function(r){if(!r.ok){throw new Error('upload HTTP '+r.status);}return r.json();}).then(function(j){return j.name||file.name;});}
function selectedFile(id){var x=q(id);return x&&x.files&&x.files[0]?x.files[0]:null;}
function wf(charName,poseName){var ckpt=v('selCheckpoint','');if(!ckpt){throw new Error('Checkpoint required');}var seed=parseInt(v('inSeed','-1'),10);if(isNaN(seed)||seed<0){seed=Math.floor(Math.random()*2147483647);}var w={'1':{class_type:'CheckpointLoaderSimple',inputs:{ckpt_name:ckpt}},'2':{class_type:'CLIPTextEncode',inputs:{text:v('positivePrompt','masterpiece'),clip:['1',1]}},'3':{class_type:'CLIPTextEncode',inputs:{text:v('negativePrompt','low quality'),clip:['1',1]}},'4':{class_type:'EmptyLatentImage',inputs:{width:parseInt(n('inWidth',512),10),height:parseInt(n('inHeight',768),10),batch_size:1}}};var model=['1',0],pos=['2',0],neg=['3',0],next=10;if(poseName&&v('selControlnet','')&&hasNode('ControlNetApplyAdvanced')){var lp=''+next++,cn=''+next++,ap=''+next++;w[lp]={class_type:'LoadImage',inputs:{image:poseName}};w[cn]={class_type:'ControlNetLoader',inputs:{control_net_name:v('selControlnet','')}};w[ap]={class_type:'ControlNetApplyAdvanced',inputs:{positive:pos,negative:neg,control_net:[cn,0],image:[lp,0],strength:n('inCnStrength',0.82),start_percent:0,end_percent:n('inCnEnd',0.75)}};pos=[ap,0];neg=[ap,1];log('Pose ControlNet active: '+poseName);}if(charName&&v('selIpadapter','')&&hasNode('IPAdapterAdvanced')){var lc=''+next++,ip=''+next++,ai=''+next++;w[lc]={class_type:'LoadImage',inputs:{image:charName}};w[ip]={class_type:'IPAdapterModelLoader',inputs:{ipadapter_file:v('selIpadapter','')}};w[ai]={class_type:'IPAdapterAdvanced',inputs:{model:model,ipadapter:[ip,0],image:[lc,0],weight:n('inIpaWeight',0.4),weight_type:v('selIpaWeightType','linear'),combine_embeds:'concat',start_at:n('inIpaStart',0.2),end_at:n('inIpaEnd',0.8),embeds_scaling:v('selEmbedsScaling','K+V w/ C penalty')}};model=[ai,0];log('Character IPAdapter active: '+charName+' combine_embeds=concat');}w['5']={class_type:'KSampler',inputs:{seed:seed,steps:parseInt(n('inSteps',25),10),cfg:n('inCfg',7),sampler_name:v('selSampler','dpmpp_2m'),scheduler:v('selScheduler','karras'),denoise:1,model:model,positive:pos,negative:neg,latent_image:['4',0]}};w['6']={class_type:'VAEDecode',inputs:{samples:['5',0],vae:['1',2]}};w['7']={class_type:'SaveImage',inputs:{filename_prefix:'comfyui_lab',images:['6',0]}};return w;}
function load(pid,count){if(count>180){done();return;}setTimeout(function(){get('/history/'+encodeURIComponent(pid)).then(function(h){var it=h[pid];var img=null;if(it&&it.outputs){Object.keys(it.outputs).forEach(function(k){var o=it.outputs[k];if(!img&&o.images&&o.images[0]){img=o.images[0];}});}if(!img){load(pid,count+1);return;}var u=base()+'/view?filename='+encodeURIComponent(img.filename)+'&subfolder='+encodeURIComponent(img.subfolder||'')+'&type='+encodeURIComponent(img.type||'output')+'&t='+Date.now();var g=q('gallery');if(g){var im=document.createElement('img');im.src=u;im.onclick=function(){window.open(u,'_blank');};g.insertBefore(im,g.firstChild);}log('Image loaded '+img.filename);done();}).catch(function(){load(pid,count+1);});},1000);}
function done(){var a=q('btnGenerate'),b=q('btnInterrupt');if(a){a.disabled=false;}if(b){b.disabled=true;}}
window.generate=function(){var a=q('btnGenerate'),b=q('btnInterrupt');if(a){a.disabled=true;}if(b){b.disabled=false;}Promise.all([uploadInput(selectedFile('fileChar')),uploadInput(selectedFile('filePose'))]).then(function(r){return post('/prompt',{prompt:wf(r[0],r[1]),client_id:'comfyui_lab_browser'});}).then(function(x){log('Queued prompt '+x.prompt_id);load(x.prompt_id,0);}).catch(function(e){log('Generate failed: '+e.message);alert(e.message);done();});};
log('ref_fix.js loaded: combine_embeds=concat');
})();
