(function(){
'use strict';
function q(id){return document.getElementById(id);}
function log(m){var b=q('logArea');var s='['+new Date().toLocaleTimeString()+'] '+m;console.log(s);if(b){b.textContent+=s+'\n';b.scrollTop=b.scrollHeight;}}
function v(id,d){var x=q(id);return x&&x.value!==''?x.value:d;}
function esc(s){return String(s||'').replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c];});}
function sentenceCut(s,max){s=String(s||'').replace(/\s+/g,' ').trim();if(s.length<=max){return s;}return s.slice(0,max).replace(/[,，.。!！?？][^,，.。!！?？]*$/,'');}
function modeFromScene(scene){var t=(scene.label+' '+scene.promise+' '+scene.content+' '+scene.openLoop).toLowerCase();if(/전투|결투|검|칼|무공|공격|베다|찌르|추격|도약|sword|fight|duel|attack|slash|leap/.test(t)){return 'Action Wide Shot';}if(/말했|속삭|고백|눈빛|분노|웃음|울음|dialogue|whisper|face|close/.test(t)){return 'Dialogue Close-up';}if(/도시|학교|교실|폐허|산|숲|밤|달|비|옥상|골목|배경|establishing/.test(t)){return 'Background / Establishing Shot';}return 'Character Stable Scene';}
function promptFromScene(scene,mode){var style=v('prodStyle','cinematic anime wuxia, dramatic lighting, detailed, clean lineart');var label=String(scene.label||'').trim();var promise=String(scene.promise||'').trim();var content=String(scene.content||'').trim();var open=String(scene.openLoop||'').trim();var camera='medium shot';if(mode==='Action Wide Shot'){camera='dynamic full body action shot, clear body motion, dramatic action pose, strong silhouette';}else if(mode==='Dialogue Close-up'){camera='emotional close-up, expressive eyes, cinematic face lighting';}else if(mode==='Background / Establishing Shot'){camera='wide establishing shot, environment focus, cinematic composition';}
return [label,promise,sentenceCut(content,360),open,camera,style,'consistent same character from reference image, no random new character'].filter(Boolean).join(', ');
}
function extractJson(text){var t=String(text||'').trim();if(!t){throw new Error('JSON 입력이 비어 있습니다.');}if(t.indexOf('```')>=0){t=t.replace(/```json/gi,'').replace(/```/g,'').trim();}var a=t.indexOf('{'),b=t.lastIndexOf('}');var aa=t.indexOf('['),bb=t.lastIndexOf(']');if(a>=0&&b>a){t=t.slice(a,b+1);}else if(aa>=0&&bb>aa){t=t.slice(aa,bb+1);}return JSON.parse(t);}
function normalizeSilverScenes(data){var scenes=Array.isArray(data)?data:(Array.isArray(data.scenes)?data.scenes:[]);var neg='low quality, blurry, bad anatomy, extra fingers, deformed fingers, text, watermark, random face, inconsistent costume';return scenes.map(function(sc,i){var mode=modeFromScene(sc);return {shot_id:'S'+String(i+1).padStart(3,'0'),order:i+1,duration_sec:4,scene_text:String(sc.content||''),subtitle:sentenceCut(sc.content||sc.promise||sc.label,95),visual_prompt:promptFromScene(sc,mode),workflow_mode:mode,exact_pose_required:mode==='Action Wide Shot'&&/정확|초식|자세|도약|검을 들어|높이|찌르|베/.test(String(sc.content||sc.label||'')),camera:mode==='Action Wide Shot'?'full body':(mode==='Dialogue Close-up'?'close-up':'medium shot'),negative_prompt:neg,status:'pending',image_url:'',silver:{label:String(sc.label||''),promise:String(sc.promise||''),openLoop:String(sc.openLoop||''),trustClaims:String(sc.trustClaims||'해당 없음'),voiceNotes:String(sc.voiceNotes||'해당 없음')}};});}
function renderLocal(shots){var box=q('llmShotList');if(!box){return;}box.innerHTML='';shots.forEach(function(s){var d=document.createElement('div');d.style.cssText='border-bottom:1px solid #333348;padding:6px 2px;color:#dfe6e9';d.innerHTML='<b style="color:#00cec9">'+esc(s.shot_id)+'</b> <span style="color:#a29bfe">'+esc(s.workflow_mode)+'</span> <span style="color:#8b93a7">'+esc(s.status)+'</span><br><b>'+esc(s.silver?s.silver.label:'')+'</b><br><span style="color:#fff">'+esc(s.subtitle)+'</span><br><span style="color:#9aa3c2">PROMPT: '+esc(s.visual_prompt).slice(0,260)+'</span>';box.appendChild(d);});}
function silverPrompt(){var scenario=v('llmScenario','').trim()||v('scenarioText','').trim();return '당신은 SilverStudio 대본 설계 AI입니다.\n\n## 프로젝트 정보\n- 타이틀 약속: (미정 — 자유롭게 제안)\n- 타겟 시청자: 청장년\n- 포맷: transformation\n- 주제: 현대 귀환 무협 오리지널 AI 애니 완결 몰아보기 — 고등학생 무림 생존 후 현실 복수 서사\n\n## SilverStudio 스킬파일 요약\n### [script_architect] 씬 아키텍처\n- skill_file: scene_architecture.skill.md\n- 작업 기준:\n씬 = 약속 + 이행 + 다음 약속.\n25초 보상 리듬. 40초 무보상 금지.\n긴장 곡선: 최종 이행 70-85% 지점.\n- 즉시 탈락 기준:\n1. 오픈 루프 없는 씬 2개+\n2. 40초 무보상\n3. 약속 조기 이행\n\n### [algorithm_hypothesis] 첫 10초/리텐션\n- skill_file: first_10_seconds_retention.skill.md\n- 작업 기준:\n5단계: Stake(0-2초)→Visual Lock(2-4초)→Curiosity Gap(4-7초)→Credibility(7-9초)→Transition(9-12초).\n리워드: 모든 씬에 다음 10초를 볼 이유. 15~25초마다 micro reward.\n금지: 인트로, 채널 인사, 타이틀 반복.\n- 즉시 탈락 기준:\n1. Stake/Curiosity Gap 누락\n2. 건너뛰어도 무방한 도입부\n3. 리워드 없는 구간\n\n### [companion_voice] 시니어 친화 음성\n- skill_file: senior_friendly_voice.skill.md\n- 작업 기준:\n동반자 톤: 함께 알아가는 동반자.\n한 문장 한 개념. 전문용어→일상어 즉시 치환.\n가족 전달 구문 2개+. 부담 없는 공유 문장.\n- 즉시 탈락 기준:\n1. 문장 과밀\n2. 전문용어 미설명\n3. 가족 전달 0개\n4. 유치한 연령 표현\n\n### [evaluation] KPE 스코어링\n- skill_file: kpe_scoring.skill.md\n- 작업 기준:\n10-KPE 채점: 각 0-10, 총 100.\n게이트: 70+ publish / 60-69 revise / 50-59 redesign / <50 reject.\n\n## 적용 지시\n위 스킬파일 기준은 선택사항이 아니라 합격 조건입니다. 특히 첫 10초 구조, 씬별 약속-이행-오픈루프, 25초 보상 리듬, 오디언스 감정 트리거, 탈락 기준을 반드시 반영하세요.\n\n## 출력 형식\n반드시 유효한 JSON만 출력하세요. 설명/인사/마크다운 코드펜스 금지. 모든 필드를 빈 문자열 없이 채우세요. 값이 없으면 "해당 없음". scenes 배열에 8-12개 씬을 생성하세요.\n\n{\n  "scenes": [\n    {\n      "label": "(씬 제목 — 필수, 빈 문자열 금지)",\n      "promise": "(이 씬에서 시청자가 얻는 구체적 가치 — 필수)",\n      "content": "(실제 대본 전문 — 필수, 최소 2문장)",\n      "openLoop": "(다음 씬으로 이어지는 예고 문장 — 마지막 씬 제외 필수)",\n      "trustClaims": "(Tier 1-2 출처: 기관명+URL 또는 해당 없음 — 필수 기입)",\n      "voiceNotes": "(속도/톤/정적 지시 — 필수, 예: 분당 130단어, 핵심 후 1초 정적)"\n    }\n  ]\n}\n\n## 원본 시나리오 / 제작 의도\n'+scenario+'\n\n지금 위 JSON 형식으로만 응답하세요.';}
function applySilverAdapter(){var btnCopy=q('btnCopyPlanner');var btnImport=q('btnImportShots');if(btnCopy){btnCopy.onclick=function(){var p=silverPrompt();navigator.clipboard.writeText(p).then(function(){log('SilverStudio LLM prompt copied to clipboard');}).catch(function(){q('llmShotJson').value=p;log('Clipboard blocked. SilverStudio prompt inserted into JSON box.');});};}
if(btnImport){btnImport.onclick=function(){try{var data=extractJson(v('llmShotJson',''));var shots=normalizeSilverScenes(data);window.SilverStudioShots=shots;var target=q('llmShotJson');if(target){target.dataset.silverShots=JSON.stringify(shots);}renderLocal(shots);log('Imported SilverStudio scenes as image shot cards: '+shots.length);var old=window.__silverShotsReady;window.__silverShotsReady=shots;}catch(e){log('SilverStudio import failed: '+e.message);alert('SilverStudio JSON Import 실패: '+e.message);}};}
}
setTimeout(function(){applySilverAdapter();log('silverstudio_adapter.js loaded: scenes[] JSON parser enabled');},1600);
})();