(function(){
'use strict';
function q(id){return document.getElementById(id);}
function log(m){var b=q('logArea');var s='['+new Date().toLocaleTimeString()+'] '+m;console.log(s);if(b){b.textContent+=s+'\n';b.scrollTop=b.scrollHeight;}}
function v(id,d){var x=q(id);return x&&x.value!==''?x.value:d;}
function esc(s){return String(s||'').replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c];});}
function sentenceCut(s,max){s=String(s||'').replace(/\s+/g,' ').trim();if(s.length<=max){return s;}return s.slice(0,max).replace(/[,，.。!！?？][^,，.。!！?？]*$/,'');}
function modeFromScene(scene){var t=(scene.label+' '+scene.promise+' '+scene.content+' '+scene.openLoop).toLowerCase();if(/전투|결투|검|칼|무공|공격|베다|찌르|추격|도약|sword|fight|duel|attack|slash|leap/.test(t)){return 'Action Wide Shot';}if(/말했|속삭|고백|눈빛|분노|웃음|울음|dialogue|whisper|face|close/.test(t)){return 'Dialogue Close-up';}if(/도시|학교|교실|폐허|산|숲|밤|달|비|옥상|골목|배경|establishing/.test(t)){return 'Background / Establishing Shot';}return 'Character Stable Scene';}
function promptFromScene(scene,mode){var style=v('prodStyle','cinematic anime wuxia, dramatic lighting, detailed, clean lineart');var label=String(scene.label||'').trim();var promise=String(scene.promise||'').trim();var content=String(scene.content||'').trim();var open=String(scene.openLoop||'').trim();var camera='medium shot';if(mode==='Action Wide Shot'){camera='dynamic full body action shot, clear body motion, dramatic action pose, strong silhouette';}else if(mode==='Dialogue Close-up'){camera='emotional close-up, expressive eyes, cinematic face lighting';}else if(mode==='Background / Establishing Shot'){camera='wide establishing shot, environment focus, cinematic composition';}
return [label,promise,sentenceCut(content,360),open,camera,style,'consistent same character from reference image, no random new character'].filter(Boolean).join(', ');
}
function trimToJson(text){var t=String(text||'').trim();if(!t){throw new Error('JSON 입력이 비어 있습니다.');}t=t.replace(/^\uFEFF/,'');if(t.indexOf('```')>=0){t=t.replace(/```json/gi,'').replace(/```/g,'').trim();}var a=t.indexOf('{'),b=t.lastIndexOf('}');var aa=t.indexOf('['),bb=t.lastIndexOf(']');if(a>=0&&b>a){return t.slice(a,b+1);}if(aa>=0&&bb>aa){return t.slice(aa,bb+1);}return t;}
function cleanJsonText(text){var t=trimToJson(text);t=t.replace(/[“”]/g,'"').replace(/[‘’]/g,"'").replace(/，/g,',').replace(/：/g,':');t=t.replace(/\r/g,'\n');t=t.replace(/\t/g,' ');t=t.replace(/,\s*([}\]])/g,'$1');return t;}
function tryParseJson(t){try{return JSON.parse(t);}catch(e){return null;}}
function parseByFunction(t){try{return (new Function('return ('+t+');'))();}catch(e){return null;}}
function extractField(objText,name){var re=new RegExp('"'+name+'"\\s*:\\s*"([\\s\\S]*?)"\\s*(?=,\\s*"(?:label|promise|content|openLoop|trustClaims|voiceNotes)"\\s*:|\\s*})');var m=objText.match(re);return m?m[1].replace(/\\n/g,'\n').replace(/\\"/g,'"').trim():'';}
function parseScenesLenient(t){var scenes=[];var si=t.indexOf('"scenes"');if(si<0){si=t.indexOf('scenes');}var arrStart=t.indexOf('[',si);var arrEnd=t.lastIndexOf(']');if(arrStart<0||arrEnd<arrStart){throw new Error('scenes 배열을 찾지 못했습니다.');}var body=t.slice(arrStart+1,arrEnd);var depth=0,start=-1;for(var i=0;i<body.length;i++){var ch=body.charAt(i);if(ch==='{'){if(depth===0){start=i;}depth++;}else if(ch==='}'){depth--;if(depth===0&&start>=0){var obj=body.slice(start,i+1);scenes.push({label:extractField(obj,'label'),promise:extractField(obj,'promise'),content:extractField(obj,'content'),openLoop:extractField(obj,'openLoop'),trustClaims:extractField(obj,'trustClaims')||'해당 없음',voiceNotes:extractField(obj,'voiceNotes')||'해당 없음'});start=-1;}}}
return {scenes:scenes};}
function extractJson(text){var t=cleanJsonText(text);var parsed=tryParseJson(t);if(parsed){return parsed;}var js=parseByFunction(t);if(js){log('JSON strict parse failed, JavaScript object parser recovered it.');return js;}var lenient=parseScenesLenient(t);if(lenient.scenes&&lenient.scenes.length>0){log('JSON strict parse failed, lenient scenes parser recovered '+lenient.scenes.length+' scenes.');return lenient;}try{JSON.parse(t);}catch(e){var pos=0;var m=String(e.message).match(/position\s+(\d+)/);if(m){pos=parseInt(m[1],10)||0;}var around=t.slice(Math.max(0,pos-80),Math.min(t.length,pos+160));throw new Error(e.message+' / near: '+around);}throw new Error('JSON 파싱 실패');}
function normalizeSilverScenes(data){var scenes=Array.isArray(data)?data:(Array.isArray(data.scenes)?data.scenes:[]);if(scenes.length===0){throw new Error('scenes 배열이 비어 있습니다.');}var neg='low quality, blurry, bad anatomy, extra fingers, deformed fingers, text, watermark, random face, inconsistent costume';return scenes.map(function(sc,i){var mode=modeFromScene(sc);return {shot_id:'S'+String(i+1).padStart(3,'0'),order:i+1,duration_sec:4,scene_text:String(sc.content||''),subtitle:sentenceCut(sc.content||sc.promise||sc.label,95),visual_prompt:promptFromScene(sc,mode),workflow_mode:mode,exact_pose_required:mode==='Action Wide Shot'&&/정확|초식|자세|도약|검을 들어|높이|찌르|베/.test(String(sc.content||sc.label||'')),camera:mode==='Action Wide Shot'?'full body':(mode==='Dialogue Close-up'?'close-up':'medium shot'),negative_prompt:neg,status:'pending',image_url:'',silver:{label:String(sc.label||''),promise:String(sc.promise||''),openLoop:String(sc.openLoop||''),trustClaims:String(sc.trustClaims||'해당 없음'),voiceNotes:String(sc.voiceNotes||'해당 없음')}};});}
function renderLocal(shots){var box=q('llmShotList');if(!box){return;}box.innerHTML='';shots.forEach(function(s){var d=document.createElement('div');d.style.cssText='border-bottom:1px solid #333348;padding:6px 2px;color:#dfe6e9';d.innerHTML='<b style="color:#00cec9">'+esc(s.shot_id)+'</b> <span style="color:#a29bfe">'+esc(s.workflow_mode)+'</span> <span style="color:#8b93a7">'+esc(s.status)+'</span><br><b>'+esc(s.silver?s.silver.label:'')+'</b><br><span style="color:#fff">'+esc(s.subtitle)+'</span><br><span style="color:#9aa3c2">PROMPT: '+esc(s.visual_prompt).slice(0,260)+'</span>';box.appendChild(d);});}
function silverPrompt(){var scenario=v('llmScenario','').trim()||v('scenarioText','').trim();return '당신은 SilverStudio 대본 설계 AI입니다. 반드시 유효한 JSON만 출력하세요. 설명/인사/마크다운 코드펜스 금지. 문자열 안의 큰따옴표는 반드시 작은따옴표로 바꾸거나 \\" 로 이스케이프하세요. 줄바꿈은 \\n으로 이스케이프하세요. 모든 필드를 빈 문자열 없이 채우세요. 값이 없으면 "해당 없음". scenes 배열에 8-12개 씬을 생성하세요.\n\n프로젝트 정보: 현대 귀환 무협 오리지널 AI 애니 완결 몰아보기 — 고등학생 무림 생존 후 현실 복수 서사.\n\n필수 기준: 첫 10초 Stake/Visual Lock/Curiosity Gap/Credibility/Transition, 씬별 약속-이행-오픈루프, 25초 보상 리듬, 40초 무보상 금지, 오픈루프 없는 씬 2개 이상 금지.\n\n반환 스키마:\n{\n  "scenes": [\n    {\n      "label": "씬 제목",\n      "promise": "이 씬에서 시청자가 얻는 구체적 가치",\n      "content": "실제 대본 전문. 최소 2문장. 내부 큰따옴표 사용 금지",\n      "openLoop": "다음 씬 예고 문장. 마지막 씬은 해당 없음",\n      "trustClaims": "Tier 1-2 출처 또는 해당 없음",\n      "voiceNotes": "분당 130단어, 핵심 후 1초 정적"\n    }\n  ]\n}\n\n원본 시나리오 / 제작 의도:\n'+scenario+'\n\n지금 JSON만 출력하세요.';}
function applySilverAdapter(){var btnCopy=q('btnCopyPlanner');var btnImport=q('btnImportShots');if(btnCopy){btnCopy.onclick=function(){var p=silverPrompt();navigator.clipboard.writeText(p).then(function(){log('SilverStudio LLM prompt copied to clipboard');}).catch(function(){q('llmShotJson').value=p;log('Clipboard blocked. SilverStudio prompt inserted into JSON box.');});};}
if(btnImport){btnImport.onclick=function(){try{var data=extractJson(v('llmShotJson',''));var shots=normalizeSilverScenes(data);window.SilverStudioShots=shots;window.__silverShotsReady=shots;var target=q('llmShotJson');if(target){target.dataset.silverShots=JSON.stringify(shots);}renderLocal(shots);log('Imported SilverStudio scenes as image shot cards: '+shots.length);}catch(e){log('SilverStudio import failed: '+e.message);alert('SilverStudio JSON Import 실패: '+e.message);}};}
}
setTimeout(function(){applySilverAdapter();log('silverstudio_adapter.js loaded: robust scenes[] JSON parser enabled');},1600);
})();